// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqszgdgwguthypeyfwxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxc3pnZGd3Z3V0aHlwZXlmd3hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM3NzA2NDgsImV4cCI6MjA0OTM0NjY0OH0._u5kGyY1VzFCkEwqhtgTjLpT42avpQiHmDnzPrEyLd0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);